### PR TITLE
Found two typos

### PR DESCRIPTION
**Pull request by tommyod**
I found two minor typos, which I added to the errata.

### CODE REVIEW

**Comment by yousuketakada** [comment]
The error on Page 115 has been already corrected in the official errata; please double-check.
Thank you.

**Comment by tommyod** [comment]
I'm a little confused. On the page opposite the dedication photograph in my book book it says "9 8 (corrected at 8th printing 2009)", so I downloaded Version 3 as per the [instructions](https://www.microsoft.com/en-us/research/people/cmbishop/#!prml-book). In Version 3, the typo on page 115 is not mentioned.

In Versions 1 and 2 the typo on page 115 *is* mentioned. Both of these versions also mention a typo on page 114 which is fixed in my version of the book - which leads me to believe that Version 3 is indeed correct. This makes me believe that the typo was found, but someone forgot to correct it.

Thoughts? I'll happily remove it from the PR if you want.

**Comment by yousuketakada** [comment]
Seems like the third (2009) printing has failed to correct the error you mentioned but mistakenly removed the corresponding erratum.
There are some instances of such a _regression_ error in the third printing, which are marked as "(the third printing only)" in my errata.

I shall pull your PR to edit and merge.

**Comment by tommyod** [comment]
Great. Thanks @yousuketakada!

**Pull request merged**
