### PR TITLE
Added sentence about Jacobian

### PR DESCRIPTION
**Pull request by tommyod**
A reader might not now that $dy / dx$ is called the Jacobian matrix in the multivariate setting, so I added a sentence about it. Looking forward to using the errata as I read the book. :+1:

### CODE REVIEW

**Comment by yousuketakada** [comment]
Thank you for your suggestion.

The Jacobian thing in the change of variables is something we learn at
multivariate calculus (probably at a freshmen's course at college), which
is prerequisite for PRML (see Preface).
So I don't think it is necessary or helpful to point out that.

Yousuke Takada

2018/12/24 23:05 "Tommy" <notifications@github.com>:

A reader might not now that $dy / dx$ is called the Jacobian matrix in the
multivariate setting, so I added a sentence about it. Looking forward to
using the errata as I read the book. 👍
------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/yousuketakada/prml_errata/pull/13
Commit Summary

   - added sentence about jacobian

File Changes

   - *M* prml_errata.pdf
   <https://github.com/yousuketakada/prml_errata/pull/13/files#diff-0> (0)
   - *M* prml_errata.tex
   <https://github.com/yousuketakada/prml_errata/pull/13/files#diff-1> (3)

Patch Links:

   - https://github.com/yousuketakada/prml_errata/pull/13.patch
   - https://github.com/yousuketakada/prml_errata/pull/13.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/yousuketakada/prml_errata/pull/13>, or mute the thread

**Comment by tommyod** [comment]
Thank you for the response. It's hard to disagree with your sentiment. I'll close the PR!

**Comment by yousuketakada** [comment]
Although the PR has been closed, I'm thinking it may be a good idea to refer to the notation of the Jacobian matrix (C.18) here because the notation is used not very often in PRML (J is used in (2.53), for example).
c1aca35d0c20d78bebfde367ab6b8b502f0475d8

**Comment by tommyod** [comment]
I agree. The way it's written now, referring to (C.18), is very clear.

**Comment by yousuketakada** [comment]
Thank you very much for your comment.

Now, could you please tell me how you want to be addressed ("Tommy  (@tommyod)" or your full name) if I should acknowledge you in my errata?
Thank you in advance.

**Comment by tommyod** [comment]
Using "Tommy (@tommyod)" is fine. Thanks!

**Pull request closed without merging**
